# Generated by Django 5.0.1 on 2024-01-22 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Categoría del producto'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
    ]
